'use client';
import {useEffect,useRef,useState} from 'react';
import {Settings,TrainFront,Ship,RotateCcw} from 'lucide-react';
import {renderToStaticMarkup} from 'react-dom/server';
import {Switch} from '@/components/ui/switch';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import type {Map as GLMap,Marker,Popup} from 'maplibre-gl';
import {decodeNetwork,prepare,pathDistance,travelDistance,along,position,type Point,type Vehicle,type Prepared} from '@/lib/transit-geometry';
const BOUNDS:[Point,Point]=[[-74.027,40.652],[-73.944,40.804]];
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const formatTime=(time:number)=>new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'2-digit',hour12:true}).format(new Date(time*1000)).replace(/\s[AP]M/,'');
function scheduleHTML(v:Vehicle,now:number){let next=v.stops.findIndex(s=>s.departure>now);if(next<0)next=v.stops.length-1;return `<section class="schedule" aria-label="Journey schedule"><header class="schedule-head"><span class="eyebrow">${v.mode==='ferry'?'NYC FERRY':'SUBWAY'} · ${escape(v.route)}</span><button class="close" aria-label="Close schedule">×</button><h2>To ${escape(v.headsign)}</h2><p>${v.live?(v.gps?'Live GPS · matched to ferry route':'Live arrivals · estimated position'):'Scheduled journey · estimated position'}</p></header><div class="stops">${v.stops.map((s,i)=>`<div class="stop ${i<next?'past':i===next?'next':''}"><time>${formatTime(s.arrival)}</time><span class="pin"></span><div>${escape(s.name)}${i===next?'<small>'+ (now>=s.arrival?'At station':'Approaching')+'</small>':''}</div></div>`).join('')}</div></section>`;}
export default function TransitMap(){
 const container=useRef<HTMLDivElement>(null);const map=useRef<GLMap|null>(null);const engine=useRef<any>(null);const popup=useRef<Popup|null>(null);const selected=useRef<string|null>(null);const entries=useRef(new Map<string,{marker:Marker;v:Prepared;previous?:number;changed:number}>());const shapes=useRef<Record<string,Point[]>>({});const ready=useRef(false);const [loaded,setLoaded]=useState(false);const [open,setOpen]=useState(false);const [pan,setPan]=useState(false);const [zoom,setZoom]=useState(false);const [subway,setSubway]=useState(false);const [ferry,setFerry]=useState(false);const [status,setStatus]=useState({subway:'Loading schedules…',ferry:'Loading schedules…'});const [notice,setNotice]=useState('Loading transit schedules…');const [downloaded,setDownloaded]=useState('');const clock=useRef(0);const lastPopup=useRef(0);
 const reset=()=>map.current?.fitBounds(BOUNDS,{padding:window.innerWidth<600?{top:66,bottom:50,left:28,right:28}:55,duration:700});
 useEffect(()=>{let cancelled=false,frame=0;let instance:GLMap;async function init(){const ml=await import('maplibre-gl');const styleResponse=await fetch('https://basemaps.cartocdn.com/gl/positron-gl-style/style.json');if(!styleResponse.ok)throw Error('Map unavailable');const style:any=await styleResponse.json();
  for(const layer of style.layers){const id=layer.id.toLowerCase();layer.paint??={};if(layer.type==='background')layer.paint['background-color']='#30383b';if(layer.type==='fill'){layer.paint['fill-color']=id.includes('water')?'#1d2529':id.includes('park')||id.includes('landcover')?'#293b35':id.includes('building')?'#354043':'#30383b';layer.paint['fill-opacity']=1;}if(layer.type==='line'){layer.paint['line-color']=id.includes('water')?'#101a20':'#101719';layer.paint['line-opacity']=id.includes('boundary')?.3:.7;}if(layer.type==='symbol'){if(id.includes('poi')||id.includes('housenumber')||id.includes('road')||id.includes('oneway')||id.includes('place_city')){layer.layout??={};layer.layout.visibility='none';}else{layer.paint['text-color']=id.includes('water')?'#758a90':'#9aa8a7';layer.paint['text-halo-color']='#293235';layer.paint['text-halo-width']=1;}}}
  if(cancelled)return;try{instance=new ml.Map({container:container.current!,style,center:[-73.986,40.733],zoom:11,attributionControl:{compact:true},dragPan:false,scrollZoom:false,boxZoom:false,doubleClickZoom:false,keyboard:false,touchZoomRotate:false,dragRotate:false,pitchWithRotate:false,fadeDuration:0});engine.current=ml;}catch{const fallback=await import('@/lib/map-fallback');engine.current=fallback;instance=new fallback.Map({container:container.current!,center:[-73.986,40.733],zoom:11}) as unknown as GLMap;}map.current=instance;instance.fitBounds(BOUNDS,{padding:window.innerWidth<600?{top:66,bottom:50,left:28,right:28}:55,duration:0});
  instance.on('load',async()=>{try{const r=await fetch('/data/network.json');if(!r.ok)throw Error();shapes.current=decodeNetwork(await r.json() as any);if(cancelled)return;const features=Object.entries(shapes.current).map(([id,coordinates])=>({type:'Feature',properties:{mode:id.startsWith('ferry')?'ferry':'subway'},geometry:{type:'LineString',coordinates}}));instance.addSource('routes',{type:'geojson',data:{type:'FeatureCollection',features} as any});instance.addLayer({id:'subway-routes',type:'line',source:'routes',filter:['==',['get','mode'],'subway'],paint:{'line-color':'#080f12','line-width':1.35,'line-opacity':.8}});instance.addLayer({id:'ferry-routes',type:'line',source:'routes',filter:['==',['get','mode'],'ferry'],paint:{'line-color':'#709097','line-width':1,'line-dasharray':[2,6],'line-opacity':.3}});ready.current=true;setLoaded(true);}catch{setNotice('Transit geometry could not load. Reload to retry.');}});
  instance.on('click',e=>{if(!(e.originalEvent.target as HTMLElement).closest('.vehicle')){popup.current?.remove();selected.current=null;}});
  const tick=()=>{if(cancelled)return;const now=Date.now()/1000+clock.current;const bounds=instance.getBounds();for(const [id,entry] of entries.current){const target=travelDistance(entry.v,now);const blend=Math.min(1,(performance.now()-entry.changed)/12000);const point=along(entry.v,entry.previous!==undefined?entry.previous+(target-entry.previous)*blend:target);entry.marker.setLngLat(point);entry.marker.getElement().style.display=bounds.contains(point)&&now<=entry.v.stops.at(-1)!.departure?'flex':'none';entry.marker.getElement().classList.toggle('selected',id===selected.current);if(id===selected.current&&popup.current){popup.current.setLngLat(point);if(now-lastPopup.current>10){const scroll=popup.current!.getElement().querySelector('.stops')?.scrollTop??0;popup.current.setHTML(scheduleHTML(entry.v,now));const el=popup.current!.getElement();el.querySelector('.close')?.addEventListener('click',()=>{popup.current?.remove();selected.current=null;});const list=el.querySelector('.stops');if(list)list.scrollTop=scroll;lastPopup.current=now;}}}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);
 }
 init().catch((error)=>{console.error('Map initialization',error);setNotice('The map could not load. Check your connection and reload.');});return()=>{cancelled=true;cancelAnimationFrame(frame);ready.current=false;entries.current.clear();instance?.remove();};},[]);
 useEffect(()=>{if(!loaded||!map.current)return;pan?map.current.dragPan.enable():map.current.dragPan.disable();if(zoom){map.current.scrollZoom.enable();map.current.doubleClickZoom.enable();map.current.touchZoomRotate.enable();map.current.touchZoomRotate.disableRotation();}else{map.current.scrollZoom.disable();map.current.doubleClickZoom.disable();map.current.touchZoomRotate.disable();}if(pan||zoom){map.current.keyboard.enable();if(!pan)map.current.keyboard.disable();}else map.current.keyboard.disable();},[pan,zoom,loaded]);
 useEffect(()=>{if(!loaded)return;let cancelled=false;const controller=new AbortController();async function update(){try{const r=await fetch(`/api/transit?subway=${subway?'live':'schedule'}&ferry=${ferry?'live':'schedule'}`,{signal:controller.signal});if(!r.ok)throw Error();const data:any=await r.json();if(cancelled)return;clock.current=data.serverTime-Date.now()/1000;setStatus(data.status);setDownloaded(new Date(data.sources.subway.downloaded).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}));setNotice(data.vehicles.length?'':'No scheduled journeys are active. Check schedule availability in settings.');const ml=engine.current;const ids=new Set<string>();for(const v of data.vehicles as Vehicle[]){if(!shapes.current[v.shape]?.length)continue;ids.add(v.id);const entry=entries.current.get(v.id);const prepared=prepare(v,shapes.current);if(entry){const old=entry.marker.getLngLat();entry.previous=pathDistance(prepared,[old.lng,old.lat]);entry.changed=performance.now();entry.v=prepared;}else{const el=document.createElement('button');el.className='vehicle '+v.mode;el.setAttribute('aria-label',`${v.mode==='ferry'?'Ferry':'Subway'} ${v.route} to ${v.headsign}. View schedule`);el.innerHTML=renderToStaticMarkup(v.mode==='ferry'?<Ship strokeWidth={1.9}/>:<TrainFront strokeWidth={1.9}/>);el.addEventListener('click',e=>{e.stopPropagation();popup.current?.remove();selected.current=v.id;const current=entries.current.get(v.id)!;const p=current.marker.getLngLat();const now=Date.now()/1000+clock.current;popup.current=new ml.Popup({closeButton:false,closeOnClick:false,maxWidth:'330px',offset:20,focusAfterOpen:false}).setLngLat(p).setHTML(scheduleHTML(current.v,now)).addTo(map.current!);popup.current!.getElement().querySelector('.close')?.addEventListener('click',()=>{popup.current?.remove();selected.current=null;});const next=popup.current!.getElement().querySelector('.next') as HTMLElement;const list=popup.current!.getElement().querySelector('.stops');if(next&&list)list.scrollTop=Math.max(0,next.offsetTop-list.getBoundingClientRect().height/3);lastPopup.current=now;});const marker=new ml.Marker({element:el}).setLngLat(position(prepared,Date.now()/1000+clock.current)).addTo(map.current!);entries.current.set(v.id,{v:prepared,marker,changed:performance.now()});}}
 for(const [id,entry] of entries.current)if(!ids.has(id)){entry.marker.remove();entries.current.delete(id);if(selected.current===id){popup.current?.remove();selected.current=null;}}
 }catch(error){if(cancelled)return;console.error("Transit update",error);setStatus({subway:'Update unavailable',ferry:'Update unavailable'});setNotice('Transit update unavailable. Retrying shortly.');}}
 update();const timer=setInterval(update,30000);return()=>{cancelled=true;controller.abort();clearInterval(timer);};},[loaded,subway,ferry]);
 return <main aria-label="New York subway and ferry map"><div className="map" ref={container}/><Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><button className="gear" aria-label="Map settings"><Settings size={23} strokeWidth={1.6}/></button></PopoverTrigger><PopoverContent align="end" sideOffset={9} className="settings"><div className="eyebrow" style={{marginBottom:8}}>City in motion</div><h2>Map settings</h2><div className="setting-row"><label htmlFor="pan">Allow panning</label><Switch id="pan" checked={pan} onCheckedChange={setPan}/></div><div className="setting-row"><label htmlFor="zoom">Allow zooming</label><Switch id="zoom" checked={zoom} onCheckedChange={setZoom}/></div><button className="reset" onClick={reset}><RotateCcw size={12} style={{display:'inline',marginRight:7}}/>Reset view</button><div className="divider"/><div className="eyebrow">Real-time data</div><div className="setting-row"><label htmlFor="subway">Subways<small>{status.subway}</small></label><Switch id="subway" checked={subway} onCheckedChange={setSubway}/></div><div className="setting-row"><label htmlFor="ferry">Ferries<small>{status.ferry}</small></label><Switch id="ferry" checked={ferry} onCheckedChange={setFerry}/></div><p className="note">By default, movement follows published timetables. Live subway locations are estimated from arrival predictions. Ferry GPS is used when available.</p><div className="divider"/><p className="note">Times are in New York local time.<br/>Schedules imported {downloaded||'from official feeds'}.<br/><a href="https://www.mta.info/developers" target="_blank" rel="noreferrer">MTA</a> & <a href="https://www.ferry.nyc/developer-tools/" target="_blank" rel="noreferrer">NYC Ferry</a> · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a> / <a href="https://carto.com/attributions" target="_blank" rel="noreferrer">CARTO</a></p></PopoverContent></Popover>{notice&&<div role="status" className="map-status">{notice}</div>}</main>;
}
